name: adventOfCode
version: 0.0.1
description: Advent of Code (http://www.adventofcode.com)
#author: Your Name <email@example.com>
#homepage: https://www.example.com

environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
  crypto: any
  more: any

dev_dependencies:
  test: '>=0.12.0 <0.13.0'
